"""DataFrame-based visualization for parameter studies and scan data."""

from paramstudy.api import contour, heatmap, line, scatter, tricontour, tripcolor
from paramstudy.metadata import ColumnMeta, ColumnMetaRegistry, make_registry
from paramstudy.options import (
    AxesDataOptions,
    AxesOptions,
    ColorOptions,
    ColorbarMode,
    ColorbarOptions,
    ContourOptions,
    FacetLayoutMode,
    FacetLayoutOptions,
    FacetOrder,
    FigureLayoutOptions,
    FigureOptions,
    LabelOptions,
    LegendOptions,
    MissingFacetPolicy,
    ScaleOptions,
    TitleOptions,
    TripcolorOptions,
    UnitOptions,
)
from paramstudy.planner import AxesSlot, FacetKey, FigurePlan, PagePlan, build_page_plan
from paramstudy.scale import UnitScale, autoscale_unit, resolve_unit_scale, scale_to_unit
from paramstudy.spec import InputMap, PlotKind, PlotSpec, ResponseMap
from paramstudy.unit import (
    CompoundUnit,
    SIPrefix,
    SimpleUnit,
    UnitLike,
    Unitless,
    parse_unit,
    unit_from_dict,
    unit_to_dict,
)

__all__ = [
    "AxesDataOptions",
    "AxesOptions",
    "AxesSlot",
    "ColorOptions",
    "ColorbarMode",
    "ColorbarOptions",
    "ColumnMeta",
    "ColumnMetaRegistry",
    "CompoundUnit",
    "ContourOptions",
    "FacetKey",
    "FacetLayoutMode",
    "FacetLayoutOptions",
    "FacetOrder",
    "FigureLayoutOptions",
    "FigureOptions",
    "FigurePlan",
    "InputMap",
    "LabelOptions",
    "LegendOptions",
    "MissingFacetPolicy",
    "PagePlan",
    "PlotKind",
    "PlotSpec",
    "ResponseMap",
    "ScaleOptions",
    "SIPrefix",
    "SimpleUnit",
    "TitleOptions",
    "TripcolorOptions",
    "tricontour",
    "tripcolor",
    "UnitLike",
    "UnitScale",
    "Unitless",
    "UnitOptions",
    "autoscale_unit",
    "build_page_plan",
    "contour",
    "heatmap",
    "line",
    "make_registry",
    "parse_unit",
    "resolve_unit_scale",
    "scale_to_unit",
    "scatter",
    "unit_from_dict",
    "unit_to_dict",
]
